server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/licenta
    password: root
    username: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: 'wqIkA6Ez4hHQtLXjm8uD'


